import type { Metadata } from "next";
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"
import "./globals.css";



export const metadata: Metadata = {
    title:"Pokémon GACHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-emerald-200 via-green-400 to-emerald-600">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
